name: Deploy to staging (main)

on:
  push: 
    branches:
      - "production"

jobs:
  redeploy_everything: 
    runs-on: ubuntu-latest
    name: Deploying everything to the production cluster
    steps:
      - uses: actions/checkout@v4
      
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.203.104.137 bash -l << 'EOF'
          source ~/.nvm/nvm.sh
          cd hello-devops && git pull origin production
          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart fe-server
          EOF