name: Deploy to staging (main)

on:
  push: 
    branches:
      - "main"

jobs:
  redeploy_everything: 
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - uses: actions/checkout@v4
      
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.110.212.91 bash -l << 'EOF'
          cd hello-devops && git pull
          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart fe-server
          EOF